# Generated by Django 4.1.7 on 2023-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=20)),
                ('Role', models.CharField(choices=[('SalesManager1', 'SalesManager1'), ('SalesManager2', 'SalesManager2'), ('SalesExecutive1', 'SalesExecutive1'), ('SalesExecutive2', 'SalesExecutive2')], max_length=20)),
                ('Address', models.CharField(max_length=150)),
                ('TCM_ID', models.CharField(max_length=20)),
                ('Set_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
