# Generated by Django 4.1.7 on 2023-02-24 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('PhoneNo', models.IntegerField()),
                ('Email', models.EmailField(max_length=40)),
                ('Location', models.TextField(max_length=100)),
                ('Product', models.CharField(choices=[('Mobile -> Brand', 'Mobile -> Brand'), ('Accessories', 'Accessories'), ('Home Applicances', 'Home Applicances'), ('AC', 'AC'), ('IT', 'IT'), ('Small Home Applicances', 'Small Home Applicances'), ('TV', 'TV'), ('Others', 'Others')], max_length=30)),
                ('Model_Description', models.TextField(max_length=100)),
                ('Product_Value', models.IntegerField()),
                ('Reason_of_leaving', models.CharField(choices=[('Out of stock', 'Out of stock'), ('Discontinued product', 'Discontinued product'), ('Pricing', 'Pricing'), ('EMI availability', 'EMI availability'), ('EMI Ineligibility', 'EMI Ineligibility'), ('Window Shopper', 'Window Shopper'), ('Upcoming Product Enquiry', 'Upcoming Product Enquiry'), ('Outdated offers', 'Oudated offers'), ('Unspecified', 'Unspecified'), ('Others', 'Others')], max_length=30)),
                ('Revisit_date', models.DateField(default=datetime.datetime(2023, 2, 24, 3, 39, 45, 576880))),
            ],
        ),
    ]
