# Generated by Django 4.1.7 on 2023-02-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=20)),
                ('Product', models.CharField(max_length=20)),
                ('Model', models.CharField(max_length=150)),
                ('Product_Value', models.IntegerField()),
                ('Reason_of_leaving', models.CharField(max_length=20)),
                ('Revist_date', models.DateTimeField()),
            ],
        ),
    ]
