# Generated by Django 4.1.7 on 2023-02-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_data',
            name='Revist_date',
        ),
    ]
