# Generated by Django 4.1.7 on 2023-02-23 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0002_remove_customer_data_revist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='Revisit_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 18, 32, 33, 857534)),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='Email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='Model',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='Name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='customer_data',
            table='Customer_Data',
        ),
    ]
