# Generated by Django 4.1.7 on 2023-02-23 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0003_customer_data_revisit_date_alter_customer_data_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='Product',
            field=models.CharField(choices=[('Out of stock', 'Out of stock'), ('Pricing', 'Pricing'), ('EMI availability', 'EMI availability'), ('EMI Ineligibility', 'EMI Ineligibility')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='Reason_of_leaving',
            field=models.CharField(choices=[('Out of stock', 'Out of stock'), ('Pricing', 'Pricing'), ('EMI availability', 'EMI availability'), ('EMI Ineligibility', 'EMI Ineligibility')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='Revisit_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 22, 47, 19, 361882)),
        ),
    ]
