# Generated by Django 4.1.7 on 2023-02-23 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerData', '0004_alter_customer_data_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='Revisit_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 23, 10, 59, 952798)),
        ),
        migrations.AlterModelTable(
            name='customer_data',
            table=None,
        ),
    ]
